apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: quota1
  labels:
    app: nginx
spec:
  # 5 > 0 > 1
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      schedulerName: scheduler-plugins-scheduler
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1