apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: quota3
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      schedulerName: scheduler-plugins-scheduler
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1