apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: ks-quota
  labels:
    app: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      name: nginx1
      labels:
        app: nginx1
        quota.scheduling.koordinator.sh/name: "ks-quota2"
    spec:
      schedulerName: koord-scheduler
      containers:
      - name: nginx1
        image: nginx
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 500m