apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: ks-quota2
  namespace: ks-quota
  labels:
    quota.scheduling.koordinator.sh/parent: "ks-quota-parent"
    quota.scheduling.koordinator.sh/is-parent: "false"
    quota.scheduling.koordinator.sh/allow-lent-resource: "true"
spec:
  max:
    cpu: 2
  min:
    cpu: 1